[package]
name = "wherenver"
version = "0.0.1"
authors = ["Xarvex"]
edition = "2024"
rust-version = "1.85.1" # cargo-msrv on 2025-08-28

description = "Enter direnv contexts from other directories"
repository = "https://codeberg.org/xarvex/wherenver"

[dependencies]
anyhow = "1.0.88"
clap = { version = "4.5.17", features = ["derive"] }
strum = { version = "0.27.2", features = ["derive"] }

[profile.release]
opt-level = 3
strip = true
lto = true
panic = "abort"
